.\" first draft by Ankur Sinha &lt;ankursinha at fedoraproject.org&gt;
.TH "fpaste" "1" "version 0.3.8.2" "Fedora Unity" ""
.SH "NAME"
fpaste \- A cli frontend for the fpaste.org pastebin
.SH "SYNOPSIS"
\fBfpaste\fR [\fIOPTION\fR]... [\fIFILE\fR]...
.SH "DESCRIPTION"
It is often useful to be able to easily paste text to the Fedora Pastebin at http://fpaste.org and this simple utility will do that and return the resulting URL so that people may examine the output. This can hopefully help folks who are for some reason stuck without X, working remotely, or any other reason they may be unable to paste something into the pastebin using a web browser.
.SH "OPTIONS"
.TP 
\fB\-\-version\fR
show program's version number and exit
.TP 
\fB\-h, \-\-help\fR
show help message and exit
.TP 
\fB\-n "NICKNAME"\fR
your nickname; default is ""
.TP 
\fB\-d "PASSWORD", \-\-password="PASSWORD"\fR
password for paste; default is ""
.TP 
\fB\-l "LANGUAGE"\fR
language of content for syntax highlighting; default is "text"; use "list" to show all 200+ supported langs
.TP 
\fB\-x "EXPIRES"\fR
time before paste is removed; default is 2592000 seconds; valid options: 1800, 21600, 86400, 604800, 2592000
.TP 
\fB\-U, \-\-URL "URL"\fR
URL of fpaste server; default is http://fpaste.org
.TP 
\fB\-P, \-\-private\fR
make paste private; default is yes; valid options: yes, no
.TP 
\fB\ \-\-rawurl\fR
return only the raw content URL; does not attempt to shorten the URL.  Suitable for use with scripts.
.br 
.TP 
\fB\-i, \-\-clipin\fR
read paste text from current X clipboard selection
.TP 
\fB\-o, \-\-clipout\fR
save returned paste URL to X clipboard
.TP 
\fB\-\-selection=CLIPBOARD\fR
specify which X clipboard to use. valid options: "primary" (default; middle\-mouse\-button paste), "secondary" (uncommon), or "clipboard" (ctrl\-v paste)
.TP 
\fB\-\-fullpath\fR
use pathname VS basename for file description(s)
.TP 
\fB\-\-pasteself\fR
paste this script itself
.TP 
\fB\-\-sysinfo\fR
paste system information
.TP 
\fB\-\-printonly\fR
print paste, but do not send
.TP 
\fB\-\-confirm\fR
print paste, and prompt for confirmation before sending
.SH "EXAMPLES"
.TP 
Paste file foo.txt at fpaste.org
.IP 
\fBfpaste foo.txt\fR
.TP 
Paste output of ifconfig to fpaste.org with description "my network config"
.IP 
\fBifconfig | fpaste \fR
.TP 
Paste mycode.py to fpaste.org with description as "problem with foo", nickname "codemonkey", and language "python"
.IP 
\fBfpaste \-n codemonkey \-l python mycode.py\fR
.TP 
Paste mouse\-selected text from the primary X selection clipboard, and then overwrite the same clipboard with the returned fpaste URL
.IP 
\fBfpaste \-io\fR
.TP 
To \fImanually paste clipboard\fR contents, run \fBfpaste\fR without file arguments so that it waits for input, then paste using mouse middle\-click, <Ctrl\-V>, or other, then press <Enter> followed by <Ctrl\-D> to finish (EOF).
.TP 
To paste the output of more than one program and/or file at a time, use the following example forms:
.IP 
\fB(lsusb ; lspci) | fpaste\fR
.br 
\fBfpaste <(lsusb) <(lspci)\fR
.br 

\fBfpaste <(fdisk \-l) /etc/grub.conf \fR
.br 
\fB(fdisk \-l ; cat /etc/grub.conf) | fpaste \fR
.br 

\fB(uname \-a ; yum repolist) | fpaste\fR
.TP 
Gather and paste various information about the running system. The info collected should be practically anonymous, and you may use the \-\-printonly or \-\-confirm options to preview what would be sent. fpaste.org URLs are also practically anonymous ([a\-zA\-Z0\-9]**4 == 14,776,336 combinations), so you may also preview it instead before giving the link out.
.IP 
\fBfpaste \-\-sysinfo\fR
.br 
\fBfpaste \-\-sysinfo \-\-confirm\fR
.br 
\fBfpaste \-\-sysinfo \-\-printonly | less\fR
.SH "BUGS"
Report bugs to: https://fedorahosted.org/fpaste/newticket
.br 
or to: Jason 'zcat' Farrell <farrellj AT gmail DOT com>.
.SH "AUTHOR"
Fedora Unity

